//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int IdRoom { get; set; }
        public int IdType { get; set; }
        public int IdGroup { get; set; }
        public string Title { get; set; }
        public int EventPackage { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Group Group { get; set; }
        public virtual Room Room { get; set; }
        public virtual Event_Type Event_Type { get; set; }
    }
}
